name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          # cache: 'npm'

      - name: Remove pnpm lock file
        run: |
          if [ -f pnpm-lock.yaml ]; then
            rm pnpm-lock.yaml
          fi

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          # cache: 'npm'

      - name: Remove pnpm lock file
        run: |
          if [ -f pnpm-lock.yaml ]; then
            rm pnpm-lock.yaml
          fi

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
